### ISSUE TITLE
Just wondering what this line does? Sorry if it should be obvious, but maybe worth documenting.

### ISSUE THREAD

**Issue by Br-Johnson** [colebrookson/Juv-Pacific-Salmon-Sealice#3]
https://github.com/colebrookson/Juv-Pacific-Salmon-Sealice/blob/382ab55ea350408c95d493bfb75252f34d6fdfe5/Code/Complete_Analysis_And_Figures_Script.R#L30

**Comment by colebrookson** [comment]
Good point on documenting, will do! Since R doesn't have a built in inverse of the %in% operator, I make my own, it's super handy!
